# Generated by Django 3.2.9 on 2022-06-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('video', models.FileField(upload_to='')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('wedding Cake', 'Wedding Cake'), ('Birthday Cake', 'Birthday Cake'), ('Snacks', 'Snacks')], max_length=100),
        ),
    ]
