# Generated by Django 3.2.9 on 2022-06-22 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20220607_1706'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvideo',
            options={'ordering': ('-date',)},
        ),
    ]
